apiVersion: v1
kind: PersistentVolume
metadata:
  name: openscap-results-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: /srv/awx/openscap_results
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openscap-results-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
