apiVersion: v1
kind: PersistentVolume
metadata:
  name: openscap-results-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  hostPath:
    path: /srv/awx/openscap_results
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - awx-control-plane
