apiVersion: v1
kind: PersistentVolume
metadata:
  name: openscap-results-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:          # for local testing; in production use NFS/CSI driver
    path: /srv/openscap_results
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openscap-results-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
