apiVersion: v1
kind: PersistentVolume
metadata:
  name: openscap-results-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: /srv/awx/openscap_results
  claimRef:
    namespace: default          # AWX jobs run in default namespace
    name: openscap-results-pvc  # PVC name to pre-bind

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openscap-results-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
