---
- name: RESET - Revert Chrony Demo State for Idempotence Test
  hosts: all
  gather_facts: no
  become: yes
  
  tasks:
    - name: 1. Stop and Disable chrony service
      ansible.builtin.service:
        name: chronyd
        state: stopped
        enabled: no
      ignore_errors: yes
      
    - name: 2. Delete main config file
      ansible.builtin.command: sudo rm -f /etc/chrony/chrony.conf
      args:
        removes: /etc/chrony/chrony.conf
