---
- name: RESET - Revert Chrony Demo State for Idempotence Test
  hosts: all
  gather_facts: no
  become: yes
  
  tasks:
    - name: 1. Stop and Disable chrony service
      ansible.builtin.service:
        name: chronyd
        state: stopped
        enabled: no
      ignore_errors: yes # Use ignore_errors in case the service is already stopped
      
    - name: 2. Delete main config file
      # Using the 'command' module with 'sudo' which was necessary for your environment
      ansible.builtin.command: sudo rm -f /etc/chrony/chrony.conf
      # The 'removes' parameter makes this task idempotent. 
      # It checks if the file is gone *before* trying to run the command.
      removes: /etc/chrony/chrony.conf
