- name: Generate SCAP XLSX
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Confirm project files exist
      command: ls -l /runner/project
      register: project_files

    - name: Show project files (for debugging)
      debug:
        var: project_files.stdout_lines

    - name: Run Python script to convert SCAP XML -> XLSX
      command: python3 /runner/project/scap_xml_to_xlsx.py
