- name: Generate SCAP XLSX
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Run Python script to convert SCAP XML -> XLSX
      command: python3 scap_xml_to_xlsx.py
      args:
        chdir: "/runner/project"  # AWX mounts the project here
