- name: "Full SCAP Scan → Fetch → XLSX"
  hosts: all
  gather_facts: no
  become: yes

  vars:
    scap_xml_remote: "/home/awxuser/scap_results.xml"
    scap_xml_local: "/runner/project/ansible-awx-lab/scap_outputs/scap_results.xml"

  tasks:

    - name: "Run SCAP scan on the remote host"
      shell: |
        oscap xccdf eval \
          --profile xccdf_org.ssgproject.content_profile_cis \
          --results {{ scap_xml_remote }} \
          /usr/share/xml/scap/ssg/content/ssg-rhel10-ds.xml
      args:
        executable: /bin/bash
      failed_when: false

    - name: "Fetch SCAP XML back to AWX project"
      fetch:
        src: "{{ scap_xml_remote }}"
        dest: "{{ scap_xml_local }}"
        flat: yes

- name: "Generate SCAP XLSX"
  hosts: localhost
  gather_facts: no
  tasks:

    - name: "Show project files for debugging"
      command: ls -l /runner/project/ansible-awx-lab
      register: project_files

    - name: "Debug project files"
      debug:
        var: project_files.stdout_lines

    - name: "Run Python script to convert SCAP XML → XLSX"
      command: python3 /runner/project/ansible-awx-lab/scap_xml_to_xlsx.py
      args:
        chdir: "/runner/project/ansible-awx-lab"
