---
- name: Run SCAP Scan, Guarantee Report Creation, and Copy to Artifacts
  hosts: all
  become: yes # Required for SCAP scan on remote hosts
  
  vars:
    report_filename: "report_{{ inventory_hostname }}.html"
    remote_report_path: "/tmp/scap/{{ report_filename }}"
    
    ee_temp_fetch_path: "/tmp/scap_ee_fetch"
    fetch_source_path: "{{ ee_temp_fetch_path }}/{{ inventory_hostname }}/tmp/scap/{{ report_filename }}"
    awx_artifact_path: "/tmp/artifacts/{{ inventory_hostname }}_{{ report_filename }}"
    
  tasks:
    # ... Tasks 1, 2, 3 (Installation, Directory, Scan) remain the same ...
    - name: Ensure scap-security-guide package is installed
      ansible.builtin.dnf:
        name: scap-security-guide
        state: present

    - name: Ensure /tmp/scap directory exists
      ansible.builtin.file:
        path: /tmp/scap
        state: directory
        mode: '0755'

    - name: Run SCAP scan using STIG profile and save report locally
      ansible.builtin.shell: |
        oscap xccdf eval \
        --profile xccdf_org.ssgproject.content_profile_stig \
        --results /tmp/scap/results_{{ inventory_hostname }}.xml \
        --report /tmp/scap/report_{{ inventory_hostname }}.html \
        /usr/share/xml/scap/ssg/content/ssg-rhel10-ds.xml
      failed_when: false
      changed_when: true

    # 4. FETCH THE FILE
    - name: Fetch report from remote host to EE temp directory
      ansible.builtin.fetch:
        src: "{{ remote_report_path }}"
        dest: "{{ ee_temp_fetch_path }}"
        flat: false

    # 4.5. CRITICAL FIX: Ensure the artifact directory exists in the EE
    - name: Ensure AWX Artifact Directory Exists
      ansible.builtin.file:
        path: /tmp/artifacts
        state: directory
        mode: '0755'
      delegate_to: localhost
      become: no
      run_once: true

    # 5. COPY THE ARTIFACT
    - name: Copy fetched report to AWX /tmp/artifacts/ directory
      ansible.builtin.copy:
        src: "{{ fetch_source_path }}"
        dest: "{{ awx_artifact_path }}"
        remote_src: yes 
      
      become: no
      delegate_to: localhost
      run_once: true

    # 5.5. **NEW PERMISSIONS FIX**
    - name: Set Universal Read Permissions on Artifacts
      ansible.builtin.file:
        path: /tmp/artifacts
        mode: '0777' # Fixes common permission issues with AWX artifact collection
        state: directory
        recurse: yes
      delegate_to: localhost
      become: no
      run_once: true
      
    # 6. CLEANUP
    - name: Cleanup /tmp/scap directory on remote host
      ansible.builtin.file:
        path: /tmp/scap
        state: absent
      when: not ansible_failed_result is defined or ansible_failed_result.ansible_module != 'fetch'
