---
- name: "Run OpenSCAP/XCCDF scan and export XML (inside AWX pod)"
  hosts: "all"
  vars:
    profile: "xccdf_org.ssgproject.content_profile_stig"
    remote_results_dir: "/openscap_results"
    awx_fetch_dir: "/tmp/awx_scap_reports"

  tasks:

    - name: "Ensure openscap and scap-security-guide packages are installed"
      ansible.builtin.package:
        name:
          - "openscap-scanner"
          - "scap-security-guide"
        state: "present"
        update_cache: "yes"
      when: "'ansible_facts.os_family' in ['RedHat', 'Debian']"

    - name: "Create results directory on remote host"
      ansible.builtin.file:
        path: "{{ remote_results_dir }}"
        state: "directory"
        mode: "0755"

    - name: "Find SSG XCCDF content file (for OS security policy)"
      ansible.builtin.find:
        paths:
          - "/usr/share/xml/scap/ssg/content"
          - "/usr/share/ssg/content"
          - "/usr/share/xml/scap"
        patterns: "*ssg*.xml"
        recurse: "yes"
      register: "ssg_files"
      failed_when: "ssg_files.matched == 0"

    - name: "Set XCCDF file variable"
      ansible.builtin.set_fact:
        xccdf_file: "{{ ssg_files.files[0].path }}"

    - name: "Show XCCDF file used"
      ansible.builtin.debug:
        msg: "Using {{ xccdf_file }}"

    - name: "Run OpenSCAP evaluation and generate XML, ARF, and HTML"
      ansible.builtin.command: >
        oscap xccdf eval
        --profile "{{ profile }}"
        --results "{{ remote_results_dir }}/{{ inventory_hostname }}.xml"
        --results-arf "{{ remote_results_dir }}/{{ inventory_hostname }}-arf.xml"
        --report "{{ remote_results_dir }}/{{ inventory_hostname }}.html"
        "{{ xccdf_file }}"
      register: "oscap_run"
      failed_when: "oscap_run.rc not in [0, 1, 2]"
      environment:
        LANG: "C.UTF-8"

    - name: "List files in remote results directory before fetch (DEBUG STEP)"
      ansible.builtin.command: "ls -lha '{{ remote_results_dir }}'"
      register: "ls_before_fetch"
      delegate_to: "{{ inventory_hostname }}"
      changed_when: "false"

    - name: "DEBUG: Show files found on remote host"
      ansible.builtin.debug:
        msg: "Remote files:\n{{ ls_before_fetch.stdout_lines | join('\n') }}"
      when: "ls_before_fetch is defined"

    - name: "Fetch SCAP XCCDF Results XML back to AWX"
      ansible.builtin.fetch:
        src: "{{ remote_results_dir }}/{{ inventory_hostname }}.xml"
        dest: "{{ awx_fetch_dir }}/"
        flat: "yes"
      delegate_to: "localhost"
      become: "no"
      when: "oscap_run is changed"

    - name: "Fetch SCAP ARF XML Results back to AWX"
      ansible.builtin.fetch:
        src: "{{ remote_results_dir }}/{{ inventory_hostname }}-arf.xml"
        dest: "{{ awx_fetch_dir }}/"
        flat: "yes"
      delegate_to: "localhost"
      become: "no"
      when: "oscap_run is changed"

    - name: "Fetch SCAP HTML Report back to AWX"
      ansible.builtin.fetch:
        src: "{{ remote_results_dir }}/{{ inventory_hostname }}.html"
        dest: "{{ awx_fetch_dir }}/"
        flat: "yes"
      delegate_to: "localhost"
      become: "no"
      when: "oscap_run is changed"

    - name: "Clean up temporary results directory on remote host"
      ansible.builtin.file:
        path: "{{ remote_results_dir }}"
        state: "absent"
