---
- name: Run SCAP Compliance Scan
  hosts: all
  become: yes
  tasks:

    # -------------------------------------------------------------------
    # NEW TASK: Ensure the necessary SCAP content is installed
    # -------------------------------------------------------------------
    - name: Ensure scap-security-guide package is installed
      ansible.builtin.dnf:
        name: scap-security-guide
        state: present
      # We already have become: yes defined at the play level, but explicitly
      # ensuring it for this critical installation task is good practice.

    - name: Ensure /tmp/scap directory exists
      file:
        path: /tmp/scap
        state: directory
        mode: '0755'

    - name: Run SCAP scan using STIG profile
      shell: >
        oscap xccdf eval
        --profile xccdf_org.ssgproject.content_profile_stig
        --results /tmp/scap/results_{{ inventory_hostname }}.xml
        --report /tmp/scap/report_{{ inventory_hostname }}.html
        /usr/share/xml/scap/ssg/content/ssg-rhel10-ds.xml
      args:
        creates: /tmp/scap/results_{{ inventory_hostname }}.xml

    # -------------------------------------------------------------------
    # CORRECTED TASK: Fetch SCAP XML results to the permanent Project path
    # -------------------------------------------------------------------
    - name: Fetch SCAP XML results
      fetch:
        src: /tmp/scap/results_{{ inventory_hostname }}.xml
        dest: "{{ playbook_dir }}/scap_results/xml/"  # <--- CORRECTED DESTINATION
        flat: yes

    # -------------------------------------------------------------------
    # CORRECTED TASK: Fetch SCAP HTML report to the permanent Project path
    # -------------------------------------------------------------------
    - name: Fetch SCAP HTML report
      fetch:
        src: /tmp/scap/report_{{ inventory_hostname }}.html
        dest: "{{ playbook_dir }}/scap_results/html/" # <--- CORRECTED DESTINATION
        flat: yes
