---
- name: Run SCAP Scan and Fetch Report to Runner's Artifacts Directory
  hosts: all
  become: yes
  vars:
    report_filename: "report_{{ inventory_hostname }}.html"
    remote_report_path: "/tmp/scap/{{ report_filename }}"
    
    # Path inside the runner pod where 'fetch' *should* put the file
    fetch_dir: "artifacts/{{ inventory_hostname }}"

  tasks:
    # ... (Tasks 1, 2, 3: Install SCAP, Create Dir, Run Scan) ...

    # 4. **CRITICAL STEP**: FETCH THE FILE
    - name: Fetch report from remote host to runner's artifacts directory
      ansible.builtin.fetch:
        src: "{{ remote_report_path }}"
        dest: "{{ fetch_dir }}"
        flat: yes # Saves the file directly as report_192.168.15.209.html
        fail_on_missing: yes # Fails if the file wasn't created on the remote host

    # 5. **CRITICAL STEP**: EXTENDED PAUSE
    - name: PAUSE FOR FILE RETRIEVAL (90 seconds to execute docker cp)
      ansible.builtin.pause:
        minutes: 1.5 
      delegate_to: localhost
      run_once: true
      become: no

    # 6. CLEANUP
    - name: Cleanup /tmp/scap directory
      ansible.builtin.file:
        path: /tmp/scap
        state: absent
