---
- name: Run SCAP scan and fetch XML
  hosts: rhel-vm
  gather_facts: no
  tasks:

    - name: Ensure SCAP Security Guide is installed
      ansible.builtin.yum:
        name: scap-security-guide
        state: present

    - name: Run SCAP scan
      ansible.builtin.shell: |
        oscap xccdf eval \
          --profile xccdf_org.ssgproject.content_profile_cis \
          --results /home/awxuser/scap_results.xml \
          /usr/share/xml/scap/ssg/content/ssg-rhel10-ds.xml
      args:
        executable: /bin/bash

    - name: Fetch SCAP XML results
      ansible.builtin.fetch:
        src: /home/awxuser/scap_results.xml
        dest: ./scap_outputs/
        flat: yes
