---
- name: Run SCAP Scan and Retrieve Reports using Forced SCP
  hosts: all
  become: yes
  vars:
    report_filename: "report_{{ inventory_hostname }}.html"
    remote_report_path: "/tmp/scap/{{ report_filename }}"
    runner_tmp_path: "/tmp/runner_sync/" 
    # NOTE: The 'ansible_user' and 'ansible_ssh_private_key_file' variables
    # are automatically injected by AWX into the execution environment.

  tasks:

    # 1. ENSURE SCAP CONTENT IS PRESENT
    - name: Ensure rsync is installed for file transfer compatibility
      ansible.builtin.dnf:
        name: rsync # Even though we use scp, rsync is good to have.
        state: present

    # 2. PREPARE SCAN DIRECTORY
    - name: Ensure /tmp/scap directory exists
      ansible.builtin.file:
        path: /tmp/scap
        state: directory
        mode: '0755'

    # 3. RUN THE SCAN (GENERATING THE FILE)
    - name: Run SCAP scan using STIG profile
      shell: |
        oscap xccdf eval \
        --profile xccdf_org.ssgproject.content_profile_stig \
        --results /tmp/scap/results_{{ inventory_hostname }}.xml \
        --report /tmp/scap/report_{{ inventory_hostname }}.html \
        /usr/share/xml/scap/ssg/content/ssg-rhel10-ds.xml
      failed_when: false

    # 4. Create runner's temporary directory
    - name: Ensure runner's temporary sync directory exists
      ansible.builtin.file:
        path: "{{ runner_tmp_path }}"
        state: directory
      delegate_to: localhost
      run_once: true
      become: no

    # 5. **CRITICAL FIX**: EXPLICITLY USE SCP TO PULL THE FILE
    - name: Force SCP pull of the report to runner's temporary directory
      ansible.builtin.shell: |
        scp -o StrictHostKeyChecking=no \
        "{{ ansible_user }}@{{ inventory_hostname }}:{{ remote_report_path }}" \
        "{{ runner_tmp_path }}"
      args:
        # Prevents shell output from being logged, reducing the chance of hitting buffer limits
        executable: /bin/bash 
      delegate_to: localhost
      run_once: true
      become: no

    # 6. **CRITICAL STEP**: EXTENDED PAUSE
    - name: PAUSE FOR FILE RETRIEVAL (90 seconds to execute docker cp)
      ansible.builtin.pause:
        minutes: 1.5 
      delegate_to: localhost
      run_once: true
      become: no

    # 7. CLEANUP
    - name: Cleanup /tmp/scap directory
      ansible.builtin.file:
        path: /tmp/scap
        state: absent
