---
- name: Run SCAP Compliance Scan and Retrieve Reports
  hosts: all
  become: yes
  tasks:

    # 1. ENSURE SCAP CONTENT IS PRESENT
    - name: Ensure scap-security-guide package is installed
      ansible.builtin.dnf:
        name: scap-security-guide
        state: present

    # 2. PREPARE SCAN DIRECTORY
    - name: Ensure /tmp/scap directory exists
      ansible.builtin.file:
        path: /tmp/scap
        state: directory
        mode: '0755'

    # 3. RUN THE SCAN (IGNORING FAILURES)
    - name: Run SCAP scan using STIG profile
      shell: >
        oscap xccdf eval
        --profile xccdf_org.ssgproject.content_profile_stig
        --results /tmp/scap/results_{{ inventory_hostname }}.xml
        --report /tmp/scap/report_{{ inventory_hostname }}.html
        /usr/share/xml/scap/ssg/content/ssg-rhel10-ds.xml
      args:
        creates: /tmp/scap/results_{{ inventory_hostname }}.xml
      failed_when: false # Crucial: Allows playbook to continue despite non-compliance

    # 4. FETCH SCAP HTML REPORT TO AWX (The guaranteed retrieval method)
    - name: Fetch SCAP HTML report to AWX persistent storage
      ansible.builtin.fetch:
        src: /tmp/scap/report_{{ inventory_hostname }}.html
        dest: "{{ playbook_dir }}/scap_reports/" # Saves to the permanent Project volume
        flat: yes

    # 5. CLEANUP
    - name: Cleanup /tmp/scap directory
      ansible.builtin.file:
        path: /tmp/scap
        state: absent
