---
- name: Run SCAP Compliance Scan and Retrieve Reports (Base64 Retrieval)
  hosts: all
  become: yes
  vars:
    report_filename: "report_{{ inventory_hostname }}.html"
    remote_report_path: "/tmp/scap/{{ report_filename }}"
    compressed_report_path: "/tmp/scap/{{ report_filename }}.gz"

  tasks:

    # ... (Tasks 1, 2, 3: Install SCAP, Create Dir, Run Scan - REMAIN UNCHANGED) ...
    # You MUST include the previous successful tasks (1, 2, and 3) here.

    # 4. COMPRESS THE REPORT
    - name: Compress the HTML report on the remote host
      ansible.builtin.shell: "gzip -c {{ remote_report_path }} > {{ compressed_report_path }}"
      changed_when: true

    # 5. READ BASE64 ENCODED CONTENT
    - name: Read the base64 encoded, compressed report content
      ansible.builtin.shell: "base64 -w 0 {{ compressed_report_path }}" # -w 0 prevents line wrapping
      register: base64_content
      changed_when: false

    # 6. PRINT BASE64 CONTENT TO JOB LOG (GUARANTEED RETRIEVAL)
    - name: Display base64 content in job log for copy/decode
      ansible.builtin.debug:
        msg: |
          ========================================================================================
          ---BEGIN BASE64 GZIP SCAP REPORT FOR {{ inventory_hostname }}---
          
          {{ base64_content.stdout }}

          ---END BASE64 GZIP SCAP REPORT FOR {{ inventory_hostname }}---
          ========================================================================================

    # 7. CLEANUP (Optional, but safe now)
    - name: Cleanup temporary files on remote host
      ansible.builtin.file:
        path: /tmp/scap
        state: absent
