---
- name: Run OpenSCAP/XCCDF scan and export XML (for AWX)
  hosts: all
  become: yes
  vars:
    # pick a profile name from your installed content (example names are shown)
    # Change this to the profile you want to evaluate on your targets.
    profile: "xccdf_org.ssgproject.content_profile_standard"

    # remote temporary directory on each host where results will be written
    remote_results_dir: "/tmp/openscap_results"

    # local (controller) directory where fetch will place the results relative to AWX job runner working dir
    # AWX will capture files fetched to this path as job artifacts; adjust if needed.
    controller_results_dir: "scap_results"

    # Fallback sets of package names by OS family.
    openscap_packages:
      RedHat:
        - openscap-scanner
        - scap-security-guide
      Debian:
        - openscap-utils
        - scap-security-guide

  tasks:
    - name: Ensure package cache updated (Debian family)
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_facts['os_family'] == 'Debian'

    - name: Install OpenSCAP + SSG packages (platform-specific)
      ansible.builtin.package:
        name: "{{ openscap_packages[ansible_facts['os_family']] | default(['openscap-scanner','scap-security-guide']) }}"
        state: present

    - name: Create remote results directory
      ansible.builtin.file:
        path: "{{ remote_results_dir }}"
        state: directory
        mode: '0755'
        owner: root
        group: root

    - name: Find SSG XCCDF data stream file on host
      ansible.builtin.find:
        paths:
          - /usr/share/xml/scap/ssg/content
          - /usr/share/ssg/content
          - /usr/share/xml/scap
        patterns: "*ssg*.xml"
        recurse: yes
        file_type: file
      register: ssg_files
      failed_when: ssg_files.matched == 0
      changed_when: false

    - name: Pick first SSG content file found
      ansible.builtin.set_fact:
        xccdf_file: "{{ ssg_files.files[0].path }}"

    - name: Show the XCCDF file we will use (debug)
      ansible.builtin.debug:
        msg: "Using XCCDF content: {{ xccdf_file }}"

    - name: Run OpenSCAP XCCDF evaluation (produces XML, ARF, and HTML)
      ansible.builtin.command: >
        oscap xccdf eval
        --profile {{ profile }}
        --results {{ remote_results_dir }}/{{ inventory_hostname }}.xml
        --results-arf {{ remote_results_dir }}/{{ inventory_hostname }}-arf.xml
        --report {{ remote_results_dir }}/{{ inventory_hostname }}.html
        {{ xccdf_file }}
      register: oscap_run
      # sometimes oscap returns non-zero when failures are found; do not fail the play unless command failed to run
      failed_when: oscap_run.rc not in [0,2]
      changed_when: true
      environment:
        LANG: "C.UTF-8"

    - name: Debug: summarize oscap run
      ansible.builtin.debug:
        var: oscap_run.stdout_lines

    - name: Ensure controller results directory exists (on controller)
      # This runs on the controller (AWX job runner host)
      delegate_to: localhost
      run_once: true
      ansible.builtin.file:
        path: "{{ controller_results_dir }}"
        state: directory
        mode: '0755'

    - name: Fetch XML, ARF and HTML results back to controller
      ansible.builtin.fetch:
        src: "{{ item }}"
        dest: "{{ controller_results_dir }}/{{ inventory_hostname }}/"
        flat: no
      loop:
        - "{{ remote_results_dir }}/{{ inventory_hostname }}.xml"
        - "{{ remote_results_dir }}/{{ inventory_hostname }}-arf.xml"
        - "{{ remote_results_dir }}/{{ inventory_hostname }}.html"
      ignore_errors: yes

    - name: (Optional) Clean up remote results (uncomment to enable)
      ansible.builtin.file:
        path: "{{ remote_results_dir }}"
        state: absent
      # uncomment the following line if you want remote results removed:
      # when: false

  # tags allow running only this job with `--tags scap` locally for testing
  tags:
    - scap
