---
- name: Run SCAP Scan, Guarantee Report Creation, and Automatically Collect Artifacts
  hosts: all
  become: yes
  
  vars:
    report_filename: "report_{{ inventory_hostname }}.html"
    remote_report_path: "/tmp/scap/{{ report_filename }}"
    # Removed the comment about 'artifacts_dir' since we are no longer using it.

  tasks:
    # 1. ENSURE SCAP CONTENT IS PRESENT
    - name: Ensure scap-security-guide package is installed
      ansible.builtin.dnf:
        name: scap-security-guide
        state: present

    # 2. PREPARE SCAN DIRECTORY
    - name: Ensure /tmp/scap directory exists
      ansible.builtin.file:
        path: /tmp/scap
        state: directory
        mode: '0755'
      # Keep changed_when: true to ensure the scan runs every time

    # 3. RUN THE SCAN
    - name: Run SCAP scan using STIG profile
      ansible.builtin.shell: |
        oscap xccdf eval \
        --profile xccdf_org.ssgproject.content_profile_stig \
        --results /tmp/scap/results_{{ inventory_hostname }}.xml \
        --report /tmp/scap/report_{{ inventory_hostname }}.html \
        /usr/share/xml/scap/ssg/content/ssg-rhel10-ds.xml
      failed_when: false
      changed_when: true

    # 4. AUTOMATICALLY COLLECT ARTIFACT (FIXED)
    - name: AUTOMATICALLY copy SCAP report to job artifacts (using relative path)
      ansible.builtin.fetch:
        src: "{{ remote_report_path }}"
        # CRITICAL FIX: The 'fetch' module automatically resolves this relative 
        # path to a directory within the Execution Environment that AWX monitors 
        # for artifacts. This bypasses the 'artifacts_dir' issue.
        dest: "fetched" 
        flat: yes
      # REMOVED: delegate_to: localhost (fetch handles the transfer implicitly)

    # 5. CLEANUP
    - name: Cleanup /tmp/scap directory
      ansible.builtin.file:
        path: /tmp/scap
        state: absent
