---
- name: Run OpenSCAP/XCCDF scan and export XML (for AWX)
  hosts: all
  become: yes
  vars:
    profile: "xccdf_org.ssgproject.content_profile_stig"
    remote_results_dir: "/tmp/openscap_results"
    controller_results_dir: "scap_results"

    openscap_packages:
      RedHat:
        - openscap-scanner
        - scap-security-guide
      Debian:
        - openscap-utils
        - scap-security-guide

  tasks:

    - name: "Update apt cache (Debian family)"
      apt:
        update_cache: yes
      when: ansible_facts.os_family == "Debian"

    - name: "Install OpenSCAP + SSG"
      package:
        name: "{{ openscap_packages[ansible_facts.os_family] | default(['openscap-scanner','scap-security-guide']) }}"
        state: present

    - name: "Create writable results directory on remote host"
      file:
        path: "{{ remote_results_dir }}"
        state: directory
        mode: "0777"

    - name: "Find SSG XCCDF content file"
      find:
        paths:
          - /usr/share/xml/scap/ssg/content
          - /usr/share/ssg/content
          - /usr/share/xml/scap
        patterns: "*ssg*.xml"
        recurse: yes
      register: ssg_files
      failed_when: ssg_files.matched == 0

    - name: "Set XCCDF file variable"
      set_fact:
        xccdf_file: "{{ ssg_files.files[0].path }}"

    - name: "Show XCCDF file used"
      debug:
        msg: "Using {{ xccdf_file }}"

    - name: "Run OpenSCAP evaluation"
      command: >
        oscap xccdf eval
        --profile {{ profile }}
        --results {{ remote_results_dir }}/{{ inventory_hostname }}.xml
        --results-arf {{ remote_results_dir }}/{{ inventory_hostname }}-arf.xml
        --report {{ remote_results_dir }}/{{ inventory_hostname }}.html
        {{ xccdf_file }}
      register: oscap_run
      failed_when: oscap_run.rc not in [0,2]
      become: yes
      environment:
        LANG: "C.UTF-8"

    - name: "Debug: summarize oscap output"
      debug:
        var: oscap_run.stdout_lines

    - name: "List generated OpenSCAP result files"
      command: ls -l {{ remote_results_dir }}
      register: ls_results
      ignore_errors: yes

    - name: "Show list of files"
      debug:
        var: ls_results.stdout_lines

    - name: "Make controller results directory"
      delegate_to: localhost
      become: no
      run_once: true
      file:
        path: "{{ controller_results_dir }}"
        state: directory
        mode: "0755"

    - name: "Fetch results back to controller"
      delegate_to: localhost
      become: no
      fetch:
        src: "{{ item }}"
        dest: "{{ controller_results_dir }}/{{ inventory_hostname }}/"
        flat: no
      loop:
        - "{{ remote_results_dir }}/{{ inventory_hostname }}.xml"
        - "{{ remote_results_dir }}/{{ inventory_hostname }}-arf.xml"
        - "{{ remote_results_dir }}/{{ inventory_hostname }}.html"
