---
- name: Run SCAP Scan, Guarantee Report Creation, and Automatically Collect Artifacts
  hosts: all
  become: yes
  
  vars:
    report_filename: "report_{{ inventory_hostname }}.html"
    remote_report_path: "/tmp/scap/{{ report_filename }}"
    # AWX automatically exposes the path to permanent artifact storage
    # We will use this special variable directly in the fetch task.
    # The 'fetch_dir' var is no longer needed.

  tasks:
    # 1. ENSURE SCAP CONTENT IS PRESENT
    - name: Ensure scap-security-guide package is installed
      ansible.builtin.dnf:
        name: scap-security-guide
        state: present

    # 2. PREPARE SCAN DIRECTORY
    - name: Ensure /tmp/scap directory exists
      ansible.builtin.file:
        path: /tmp/scap
        state: directory
        mode: '0755'
      # Keep changed_when: true to ensure the scan runs every time

    # 3. RUN THE SCAN
    - name: Run SCAP scan using STIG profile
      ansible.builtin.shell: |
        oscap xccdf eval \
        --profile xccdf_org.ssgproject.content_profile_stig \
        --results /tmp/scap/results_{{ inventory_hostname }}.xml \
        --report /tmp/scap/report_{{ inventory_hostname }}.html \
        /usr/share/xml/scap/ssg/content/ssg-rhel10-ds.xml
      failed_when: false
      changed_when: true

    # 4. AUTOMATICALLY COLLECT ARTIFACT (Replacing Fetch, Pause, and Cleanup)
    - name: AUTOMATICALLY copy SCAP report to job artifacts
      ansible.builtin.fetch:
        src: "{{ remote_report_path }}"
        # CRITICAL: Use the AWX environment variable 'artifacts_dir' 
        # to ensure the file is saved permanently to the job's artifact storage.
        dest: "{{ artifacts_dir }}/"
        flat: yes
      # Fetch must run on the control node/EE to access artifacts_dir
      delegate_to: localhost
      # We delegate to localhost, but the file fetch occurs for each host.

    # 5. CLEANUP
    - name: Cleanup /tmp/scap directory
      ansible.builtin.file:
        path: /tmp/scap
        state: absent
