- name: Run SCAP Scan, Guarantee Report Creation, and Copy to Artifacts
  hosts: all
  become: yes
  
  vars:
    report_filename: "report_{{ inventory_hostname }}.html"
    remote_report_path: "/tmp/scap/{{ report_filename }}"
    
    # Path where 'fetch' saves the files *inside* the Execution Environment (EE)
    ee_temp_fetch_path: "/tmp/scap_ee_fetch"
    
    # The EXACT path created by the fetch module for each host:
    # Example: /tmp/scap_ee_fetch/192.168.1.10/tmp/scap/report_192.168.1.10.html
    fetch_source_path: "{{ ee_temp_fetch_path }}/{{ inventory_hostname }}/tmp/scap/{{ report_filename }}"
    
    # THE AWX ARTIFACT DESTINATION (must be inside the EE)
    awx_artifact_path: "/tmp/artifacts/{{ inventory_hostname }}_{{ report_filename }}"
    
  tasks:
    # 1. ENSURE SCAP CONTENT IS PRESENT
    - name: Ensure scap-security-guide package is installed
      ansible.builtin.dnf:
        name: scap-security-guide
        state: present

    # 2. PREPARE SCAN DIRECTORY
    - name: Ensure /tmp/scap directory exists
      ansible.builtin.file:
        path: /tmp/scap
        state: directory
        mode: '0755'

    # 3. RUN THE SCAN
    - name: Run SCAP scan using STIG profile and save report locally
      ansible.builtin.shell: |
        oscap xccdf eval \
        --profile xccdf_org.ssgproject.content_profile_stig \
        --results /tmp/scap/results_{{ inventory_hostname }}.xml \
        --report /tmp/scap/report_{{ inventory_hostname }}.html \
        /usr/share/xml/scap/ssg/content/ssg-rhel10-ds.xml
      failed_when: false
      changed_when: true

    # 4. FETCH THE FILE from the remote host to the Execution Environment
    - name: Fetch report from remote host to EE temp directory
      ansible.builtin.fetch:
        src: "{{ remote_report_path }}"
        dest: "{{ ee_temp_fetch_path }}"
        flat: false # Keep the path structure

    # 5. FINAL ARTIFACT STEP: Copy the fetched report to the AWX artifact directory
    # This task uses the standard 'copy' module which is guaranteed to be in your EE.
    - name: Copy fetched report to AWX /tmp/artifacts/ directory
      ansible.builtin.copy:
        src: "{{ fetch_source_path }}"
        dest: "{{ awx_artifact_path }}"
        remote_src: yes # The source file is already inside the EE container
      
      # *** THIS IS THE CRITICAL LINE ***
      # Ensures the copy happens *inside* the Execution Environment container
      delegate_to: localhost
      run_once: true
      
    # 6. CLEANUP
    - name: Cleanup /tmp/scap directory on remote host
      ansible.builtin.file:
        path: /tmp/scap
        state: absent
      # Only run cleanup if the fetch task was successful (task name check is robust)
      when: not ansible_failed_result is defined or ansible_failed_result.ansible_module != 'fetch'
