---
- name: "Run OpenSCAP/XCCDF scan and export XML (inside AWX pod)"
  hosts: "localhost"
  connection: "local"
  become: yes

  vars:
    profile: "xccdf_org.ssgproject.content_profile_stig"
    results_dir: "/openscap_results"

  tasks:

    - name: "Ensure OpenSCAP and SSG are installed"
      package:
        name:
          - "openscap-scanner"
          - "scap-security-guide"
        state: "present"

    - name: "Create results directory inside pod"
      file:
        path: "{{ results_dir }}"
        state: "directory"
        mode: "0755"

    - name: "Find SSG XCCDF content file"
      find:
        paths:
          - "/usr/share/xml/scap/ssg/content"
          - "/usr/share/ssg/content"
          - "/usr/share/xml/scap"
        patterns: "*ssg*.xml"
        recurse: yes
      register: "ssg_files"
      failed_when: "ssg_files.matched == 0"

    - name: "Set XCCDF file variable"
      set_fact:
        xccdf_file: "{{ ssg_files.files[0].path }}"

    - name: "Show XCCDF file used"
      debug:
        msg: "Using {{ xccdf_file }}"

    - name: "Run OpenSCAP evaluation (XML, ARF, HTML)"
      command: >
        oscap xccdf eval
        --profile "{{ profile }}"
        --results "{{ results_dir }}/{{ inventory_hostname }}.xml"
        --results-arf "{{ results_dir }}/{{ inventory_hostname }}-arf.xml"
        --report "{{ results_dir }}/{{ inventory_hostname }}.html"
        "{{ xccdf_file }}"
      environment:
        LANG: "C.UTF-8"
      register: "oscap_run"
      failed_when: "oscap_run.rc not in [0,1,2]"

    - name: "Debug: show files created in results directory"
      command: "ls -lh \"{{ results_dir }}\""
      register: "ls_results"

    - name: "Show list of result files"
      debug:
        var: "ls_results.stdout_lines"
