---
- name: Run SCAP Compliance Scan
  hosts: all
  become: yes
  tasks:

    - name: Ensure /tmp/scap directory exists
      file:
        path: /tmp/scap
        state: directory
        mode: '0755'

    - name: Run SCAP scan using STIG profile
      shell: >
        oscap xccdf eval
        --profile xccdf_org.ssgproject.content_profile_stig
        --results /tmp/scap/results_{{ inventory_hostname }}.xml
        --report /tmp/scap/report_{{ inventory_hostname }}.html
        /usr/share/xml/scap/ssg/content/ssg-rhel10-ds.xml
      args:
        creates: /tmp/scap/results_{{ inventory_hostname }}.xml

    - name: Fetch SCAP XML results
      fetch:
        src: /tmp/scap/results_{{ inventory_hostname }}.xml
        dest: ./scap_results/
        flat: yes

    - name: Fetch SCAP HTML report
      fetch:
        src: /tmp/scap/report_{{ inventory_hostname }}.html
        dest: ./scap_results/
        flat: yes
