---
- name: Run SCAP Scan and Save Report to Local Control Node
  hosts: all
  become: yes # Required for tasks running on remote hosts (SCAP scan, cleanup)
  
  vars:
    # Remote paths (unchanged)
    report_filename: "report_{{ inventory_hostname }}.html"
    remote_report_path: "/tmp/scap/{{ report_filename }}"
    
    # Execution Environment temporary fetch path
    ee_temp_fetch_path: "/tmp/scap_ee_fetch"
    fetch_source_path: "{{ ee_temp_fetch_path }}/{{ inventory_hostname }}/tmp/scap/{{ report_filename }}"
    
    # CRITICAL FIX: Changed to a user-owned path (~ is represented by ansible_env.HOME)
    # The reports will be stored under the home directory of the user running this playbook.
    local_storage_dir: "{{ lookup('env', 'HOME') }}/ansible_reports/scap"
    
    # Destination path on the control node for the final report
    final_local_report_path: "{{ local_storage_dir }}/{{ report_filename }}"
    
  tasks:
    # --- Scanning Tasks (Remote Host, requires BECOME) ---
    
    - name: Ensure scap-security-guide package is installed
      ansible.builtin.dnf:
        name: scap-security-guide
        state: present

    - name: Ensure /tmp/scap directory exists on remote host
      ansible.builtin.file:
        path: /tmp/scap
        state: directory
        mode: '0755'

    - name: Run SCAP scan using STIG profile and save report locally
      ansible.builtin.shell: |
        oscap xccdf eval \
        --profile xccdf_org.ssgproject.content_profile_stig \
        --results /tmp/scap/results_{{ inventory_hostname }}.xml \
        --report /tmp/scap/report_{{ inventory_hostname }}.html \
        /usr/share/xml/scap/ssg/content/ssg-rhel10-ds.xml
      failed_when: false
      changed_when: true

    - name: Fetch report from remote host to EE temp directory
      ansible.builtin.fetch:
        src: "{{ remote_report_path }}"
        dest: "{{ ee_temp_fetch_path }}"
        flat: false
        
    # --- Local Storage Tasks (Control Node, requires NO BECOME) ---
    
    - name: 1. Ensure the final local storage directory exists
      # The path uses lookup('env', 'HOME') to safely reference the user's home directory.
      ansible.builtin.file:
        path: "{{ local_storage_dir }}"
        state: directory
        mode: '0755'
      delegate_to: localhost
      run_once: true
      become: no # Explicitly run as the current user, without sudo.

    - name: 2. Copy the report from the fetch temp path to the final local storage directory
      ansible.builtin.copy:
        src: "{{ fetch_source_path }}"
        dest: "{{ final_local_report_path }}"
        remote_src: yes
      delegate_to: localhost
      become: no # Explicitly run as the current user, without sudo.

    - name: Print Local Report Path to Job Output
      ansible.builtin.debug:
        msg: "SCAP Report for {{ inventory_hostname }} saved locally at: {{ final_local_report_path }}"
        
    # --- CLEANUP (Remote Host, requires BECOME) ---
    
    - name: Cleanup /tmp/scap directory on remote host
      ansible.builtin.file:
        path: /tmp/scap
        state: absent
      when: not ansible_failed_result is defined or ansible_failed_result.ansible_module != 'fetch'
