---
- name: Run SCAP Scan and Retrieve Reports using Synchronize Module
  hosts: all
  become: yes # Only apply to remote host tasks (192.168.15.209)
  vars:
    report_filename: "report_{{ inventory_hostname }}.html"
    remote_report_path: "/tmp/scap/{{ report_filename }}"
    runner_tmp_path: "/tmp/runner_sync/" # A dedicated directory in the EE's temp filesystem

  tasks:

    # ... (Tasks 1, 2, 3: Install SCAP, Create Dir, Run Scan - REMAIN UNCHANGED) ...
    # These tasks run on the remote host (192.168.15.209) and need 'become: yes' (inherited from the play)

    # 4. **FIXED**: Create a temporary, dedicated folder inside the Execution Environment (localhost)
    - name: Ensure runner's temporary sync directory exists
      ansible.builtin.file:
        path: "{{ runner_tmp_path }}"
        state: directory
      delegate_to: localhost
      run_once: true
      become: no # <<< CRITICAL FIX: The runner doesn't need sudo for local /tmp/

    # 5. **FIXED**: SYNCHRONIZE (Pull) the file from the remote host to the runner's ephemeral /tmp/
    - name: Synchronize (rsync) report from remote host to runner's temporary directory
      ansible.posix.synchronize:
        src: "{{ remote_report_path }}"
        dest: "{{ runner_tmp_path }}"
        mode: pull
      delegate_to: "{{ inventory_hostname }}"
      run_once: true
      become: no # <<< CRITICAL FIX: The synchronize module is pulling, not needing privilege escalation on the runner

    # 6. **CRITICAL STEP**: PAUSE THE EXECUTION
    - name: PAUSE FOR FILE RETRIEVAL (60 seconds to execute docker cp)
      ansible.builtin.pause:
        minutes: 1
      delegate_to: localhost
      run_once: true
      become: no # <<< CRITICAL FIX: No sudo needed for a local pause

    # 7. CLEANUP
    - name: Cleanup /tmp/scap directory
      ansible.builtin.file:
        path: /tmp/scap
        state: absent
