---
- name: "Run OpenSCAP/XCCDF scan inside AWX pod"
  hosts: localhost
  connection: local
  become: no

  vars:
    profile: "xccdf_org.ssgproject.content_profile_stig"
    remote_results_dir: "/openscap_results"

  tasks:

    - name: "Ensure results directory exists in PVC"
      ansible.builtin.file:
        path: "{{ remote_results_dir }}"
        state: "directory"
        mode: "0755"

    - name: "Set XCCDF file path"
      ansible.builtin.set_fact:
        xccdf_file: "/usr/share/xml/scap/ssg/content/ssg-rhel10-ds.xml"

    - name: "Show XCCDF file used"
      ansible.builtin.debug:
        msg: "Using XCCDF file: {{ xccdf_file }}"

    - name: "Run OpenSCAP evaluation and generate XML, ARF, and HTML"
      ansible.builtin.command: >
        oscap xccdf eval
        --profile "{{ profile }}"
        --results "{{ remote_results_dir }}/{{ inventory_hostname }}.xml"
        --results-arf "{{ remote_results_dir }}/{{ inventory_hostname }}-arf.xml"
        --report "{{ remote_results_dir }}/{{ inventory_hostname }}.html"
        "{{ xccdf_file }}"
      register: oscap_run
      failed_when: "oscap_run.rc not in [0, 1, 2]"
      environment:
        LANG: "C.UTF-8"

    - name: "List files in PVC after scan"
      ansible.builtin.command:
        cmd: "ls -lha '{{ remote_results_dir }}'"
      register: ls_results
      changed_when: false

    - name: "DEBUG: Show SCAP result files in PVC"
      ansible.builtin.debug:
        msg: "Files in PVC:\n{{ ls_results.stdout_lines | join('\n') }}"
