---
- name: Run SCAP Scan, Guarantee Report Creation, and Directly Copy to Artifacts
  hosts: all
  become: yes
  
  vars:
    report_filename: "report_{{ inventory_hostname }}.html"
    remote_report_path: "/tmp/scap/{{ report_filename }}"
    # Define a known temporary spot inside the Execution Environment (EE)
    ee_temp_fetch_path: "/tmp/scap_ee_fetch"
    
  tasks:
    # 1. ENSURE SCAP CONTENT IS PRESENT
    - name: Ensure scap-security-guide package is installed
      ansible.builtin.dnf:
        name: scap-security-guide
        state: present

    # 2. PREPARE SCAN DIRECTORY
    - name: Ensure /tmp/scap directory exists
      ansible.builtin.file:
        path: /tmp/scap
        state: directory
        mode: '0755'

    # 3. RUN THE SCAN
    - name: Run SCAP scan using STIG profile
      ansible.builtin.shell: |
        oscap xccdf eval \
        --profile xccdf_org.ssgproject.content_profile_stig \
        --results /tmp/scap/results_{{ inventory_hostname }}.xml \
        --report /tmp/scap/report_{{ inventory_hostname }}.html \
        /usr/share/xml/scap/ssg/content/ssg-rhel10-ds.xml
      failed_when: false
      changed_when: true

    # 4. STEP 1: Fetch the file from the remote host to a temporary location in the EE
    - name: Fetch report from remote host to EE temp directory
      ansible.builtin.fetch:
        src: "{{ remote_report_path }}"
        dest: "{{ ee_temp_fetch_path }}"
        flat: yes # Saves directly as /tmp/scap_ee_fetch/report_filename.html

    # 5. STEP 2 (The Artifact Fix): Copy the file from the EE temp location to the permanent artifact store
    - name: Copy fetched report to permanent AWX artifact storage
      ansible.builtin.copy:
        # CORRECTED SOURCE PATH: We only use the base directory + the filename
        # (Removed the inventory_hostname subdirectory because flat: yes was used)
        src: "{{ ee_temp_fetch_path }}/{{ remote_report_path | basename }}" 
        # Destination is the highly reliable path AWX monitors for job artifacts
        dest: "{{ lookup('env', 'AWX_TASK_TMPDIR') }}/artifacts/"
        remote_src: yes
      delegate_to: localhost
      changed_when: true
      become: no # Prevents 'sudo: command not found' error

    # 6. CLEANUP
    - name: Cleanup /tmp/scap directory
      ansible.builtin.file:
        path: /tmp/scap
        state: absent
