---
- name: Perform SCAP Security Scan and Collect Results
  hosts: all
  gather_facts: yes
  become: yes

  vars:
    # Use ansible_distribution_major_version to dynamically set the file
    rhel_version: "{{ ansible_distribution_major_version }}"
    # Define the compliance profile to use (e.g., RHEL 8 CIS Benchmark)
    scap_profile: "xccdf_org.ssgproject.content_profile_cis"
    # ... (other vars remain the same)
    
  tasks:
    # ... (Task 1 and 2 remain the same)

    - name: Set dynamic path for SCAP content file
      ansible.builtin.set_fact:
        scap_content_path: "/usr/share/xml/scap/ssg/content/ssg-rhel{{ rhel_version }}-ds.xml"

    - name: 3. Perform the SCAP compliance scan
      ansible.builtin.command:
        # The oscap command now uses the dynamic path: ssg-rhel10-ds.xml
        cmd: >
          oscap xccdf eval 
          --profile {{ scap_profile }} 
          --results-arf {{ remote_report_dir }}/{{ report_filename | replace('.html', '.xml') }} 
          --report {{ remote_report_dir }}/{{ report_filename }} 
          {{ scap_content_path }}
      args:
        # Check if the dynamic file exists before running the scan
        creates: "{{ remote_report_dir }}/{{ report_filename }}"
      register: scan_result

    # ... (Tasks 4 and 5 remain the same)

    - name: 4. Create local archive directory on AWX EE
      ansible.builtin.file:
        path: "{{ local_archive_dir }}/{{ ansible_hostname }}"
        state: directory
      delegate_to: localhost

    - name: 5. Fetch the SCAP report results
      ansible.builtin.fetch:
        src: "{{ remote_report_dir }}/{{ report_filename }}"
        dest: "{{ local_archive_dir }}/{{ ansible_hostname }}/"
        flat: yes
      delegate_to: localhost

