---
- name: Run SCAP Compliance Scan and Retrieve Reports
  hosts: all
  become: yes
  vars:
    report_filename: "report_{{ inventory_hostname }}.html"
    remote_report_path: "/tmp/scap/{{ report_filename }}"
    local_fetch_path: "{{ playbook_dir }}/scap_retrieved/" # New local directory path in AWX project

  tasks:

    # ... (Tasks 1, 2, 3: Install SCAP, Create Dir, Run Scan - REMAIN UNCHANGED) ...

    # 4. GUARANTEED RETRIEVAL: READ THE HTML CONTENT FROM THE REMOTE HOST
    - name: Read the SCAP HTML report file content
      ansible.builtin.shell: "cat {{ remote_report_path }}"
      register: scap_report_content
      changed_when: false

    # 5. GUARANTEED RETRIEVAL: Write the content to a new file in the EE's /tmp directory
    # This bypasses the log truncation issue by saving it as a clean text file.
    - name: Write clean content to temporary file in execution environment
      ansible.builtin.copy:
        content: "{{ scap_report_content.stdout }}"
        dest: "/tmp/clean_{{ report_filename }}"
      delegate_to: localhost
      run_once: true

    # 6. FINAL RETRIEVAL ATTEMPT: Fetch the clean file from the EE's /tmp/ to the AWX Project Volume
    - name: Fetch the clean HTML file to AWX Project Volume
      ansible.builtin.fetch:
        src: "/tmp/clean_{{ report_filename }}"
        dest: "{{ local_fetch_path }}"
        flat: true
      delegate_to: localhost
      run_once: true

    # 7. CLEANUP
    - name: Cleanup /tmp/scap directory
      ansible.builtin.file:
        path: /tmp/scap
        state: absent
