---
- name: Run SCAP Compliance Scan and Retrieve Reports
  hosts: all
  become: yes
  vars:
    report_filename: "report_{{ inventory_hostname }}.html"
    remote_report_path: "/tmp/scap/{{ report_filename }}"

  tasks:

    # 1. ENSURE SCAP CONTENT IS PRESENT
    - name: Ensure scap-security-guide package is installed
      ansible.builtin.dnf:
        name: scap-security-guide
        state: present

    # 2. PREPARE SCAN DIRECTORY
    - name: Ensure /tmp/scap directory exists
      ansible.builtin.file:
        path: /tmp/scap
        state: directory
        mode: '0755'

    # 3. RUN THE SCAN (IGNORING FAILURES)
    - name: Run SCAP scan using STIG profile
      shell: |
        oscap xccdf eval \
        --profile xccdf_org.ssgproject.content_profile_stig \
        --results /tmp/scap/results_{{ inventory_hostname }}.xml \
        --report /tmp/scap/report_{{ inventory_hostname }}.html \
        /usr/share/xml/scap/ssg/content/ssg-rhel10-ds.xml
      args:
        # NOTE: Removing 'creates' argument to force a fresh scan every time
        # This guarantees the file is newly generated.
      failed_when: false

    # 4. GUARANTEED RETRIEVAL: READ THE HTML CONTENT FROM THE REMOTE HOST
    # This must run immediately after the scan.
    - name: Read the SCAP HTML report file content
      ansible.builtin.shell: "cat {{ remote_report_path }}"
      register: scap_report_content
      changed_when: false

    # 5. GUARANTEED RETRIEVAL: PRINT RAW CONTENT TO JOB LOG (STDOUT)
    - name: Display report content in job log for copy/paste retrieval
      ansible.builtin.debug:
        msg: |
          ========================================================================================
          ---BEGIN SCAP REPORT FOR {{ inventory_hostname }}---
          
          {{ scap_report_content.stdout }}

          ---END SCAP REPORT FOR {{ inventory_hostname }}---
          ========================================================================================
    
    # *** CLEANUP TASK HAS BEEN TEMPORARILY REMOVED ***
