---
- name: Run SCAP Compliance Scan and Stage Reports
  hosts: all
  become: yes
  tasks:

    # 1. ENSURE SCAP CONTENT IS PRESENT
    - name: Ensure scap-security-guide package is installed
      ansible.builtin.dnf:
        name: scap-security-guide
        state: present

    # 2. INSTALL AND START WEB SERVER FOR RETRIEVAL (NEW)
    - name: Ensure Nginx is installed
      ansible.builtin.dnf:
        name: nginx
        state: present

    - name: Ensure Nginx service is running
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes

    # 3. PREPARE SCAN DIRECTORY
    - name: Ensure /tmp/scap directory exists
      file:
        path: /tmp/scap
        state: directory
        mode: '0755'

    # 4. RUN THE SCAN
    - name: Run SCAP scan using STIG profile
      shell: >
        oscap xccdf eval
        --profile xccdf_org.ssgproject.content_profile_stig
        --results /tmp/scap/results_{{ inventory_hostname }}.xml
        --report /tmp/scap/report_{{ inventory_hostname }}.html
        /usr/share/xml/scap/ssg/content/ssg-rhel10-ds.xml
      args:
        creates: /tmp/scap/results_{{ inventory_hostname }}.xml

    # 5. STAGE THE REPORT TO THE WEB ROOT (NEW)
    - name: Copy HTML report to Nginx web root
      ansible.builtin.copy:
        src: /tmp/scap/report_{{ inventory_hostname }}.html
        dest: /usr/share/nginx/html/scap_report_{{ inventory_hostname }}.html
        remote_src: yes
        owner: nginx
        group: nginx
        mode: '0644'
        
    # 6. CLEANUP (Removing fetch tasks as they are no longer needed)
    - name: Cleanup /tmp/scap directory
      ansible.builtin.file:
        path: /tmp/scap
        state: absent
