---
- name: Run SCAP Scan and Save Report to Local Control Node
  hosts: all
  become: yes
  
  vars:
    # Remote paths (unchanged)
    report_filename: "report_{{ inventory_hostname }}.html"
    remote_report_path: "/tmp/scap/{{ report_filename }}"
    
    # Execution Environment temporary fetch path (UNCHANGED from original)
    ee_temp_fetch_path: "/tmp/scap_ee_fetch"
    fetch_source_path: "{{ ee_temp_fetch_path }}/{{ inventory_hostname }}/tmp/scap/{{ report_filename }}"
    
    # NEW: Local storage directory on the control node
    # Reports will be stored here. Create this directory before running.
    local_storage_dir: "/ansible_reports/scap"
    
    # NEW: Destination path on the control node for the final report
    final_local_report_path: "{{ local_storage_dir }}/{{ report_filename }}"
    
  tasks:
    # --- SCANNING (UNCHANGED) ---

    - name: Ensure scap-security-guide package is installed
      ansible.builtin.dnf:
        name: scap-security-guide
        state: present

    - name: Ensure /tmp/scap directory exists on remote host
      ansible.builtin.file:
        path: /tmp/scap
        state: directory
        mode: '0755'

    - name: Run SCAP scan using STIG profile and save report locally
      ansible.builtin.shell: |
        oscap xccdf eval \
        --profile xccdf_org.ssgproject.content_profile_stig \
        --results /tmp/scap/results_{{ inventory_hostname }}.xml \
        --report /tmp/scap/report_{{ inventory_hostname }}.html \
        /usr/share/xml/scap/ssg/content/ssg-rhel10-ds.xml
      failed_when: false
      changed_when: true

    - name: Fetch report from remote host to EE temp directory
      ansible.builtin.fetch:
        src: "{{ remote_report_path }}"
        dest: "{{ ee_temp_fetch_path }}"
        flat: false
        
    # --- LOCAL STORAGE (REPLACES S3 UPLOAD) ---
    
    - name: 1. Ensure the final local storage directory exists
      ansible.builtin.file:
        path: "{{ local_storage_dir }}"
        state: directory
        mode: '0755'
      delegate_to: localhost
      run_once: true

    - name: 2. Copy the report from the fetch temp path to the final local storage directory
      # This task moves the file from where `fetch` put it, to a permanent,
      # well-known location on the control node.
      ansible.builtin.copy:
        src: "{{ fetch_source_path }}"
        dest: "{{ final_local_report_path }}"
        remote_src: yes # Source is on the control node itself
      delegate_to: localhost

    - name: Print Local Report Path to Job Output
      ansible.builtin.debug:
        msg: "SCAP Report for {{ inventory_hostname }} saved locally at: {{ final_local_report_path }}"
        
    # --- CLEANUP (UNCHANGED) ---
    
    - name: Cleanup /tmp/scap directory on remote host
      ansible.builtin.file:
        path: /tmp/scap
        state: absent
      when: not ansible_failed_result is defined or ansible_failed_result.ansible_module != 'fetch'
