---
- name: Perform SCAP Security Scan and Collect Results
  hosts: all
  gather_facts: yes
  become: yes

  vars:
    # Define the compliance profile to use (e.g., RHEL 8 CIS Benchmark)
    scap_profile: "xccdf_org.ssgproject.content_profile_cis"
    # Define the output directory on the target host
    remote_report_dir: "/var/tmp/scap_reports"
    # Define the filename for the report
    report_filename: "scap_report_{{ ansible_hostname }}_{{ ansible_date_time.iso8601 }}.html"
    # Define the local directory on the control node (where AWX saves artifacts)
    local_archive_dir: "/tmp/scap_archive" # This path is local to the AWX EE

  tasks:
    - name: 1. Ensure OpenSCAP packages are installed
      ansible.builtin.package:
        name:
          - openscap-scanner
          - scap-security-guide
        state: present
      register: scap_install

    - name: 2. Ensure remote report directory exists
      ansible.builtin.file:
        path: "{{ remote_report_dir }}"
        state: directory
        mode: '0700' # Secure permissions

    - name: 3. Perform the SCAP compliance scan
      ansible.builtin.command:
        # The oscap command runs the scan using the defined profile and outputs an HTML report
        cmd: >
          oscap xccdf eval 
          --profile {{ scap_profile }} 
          --results-arf {{ remote_report_dir }}/{{ report_filename | replace('.html', '.xml') }} 
          --report {{ remote_report_dir }}/{{ report_filename }} 
          /usr/share/xml/scap/ssg/content/ssg-rhel8-ds.xml
      args:
        # This makes the task idempotent: only run the scan if the final report doesn't exist
        creates: "{{ remote_report_dir }}/{{ report_filename }}"
      register: scan_result

    - name: 4. Create local archive directory on AWX EE
      ansible.builtin.file:
        path: "{{ local_archive_dir }}/{{ ansible_hostname }}"
        state: directory
      delegate_to: localhost

    - name: 5. Fetch the SCAP report results
      ansible.builtin.fetch:
        src: "{{ remote_report_dir }}/{{ report_filename }}"
        dest: "{{ local_archive_dir }}/{{ ansible_hostname }}/"
        flat: yes
      delegate_to: localhost
